DoxaFinal/Controllers/FormController.cs
using Microsoft.AspNetCore.Mvc;

namespace DoxaFinal.Controllers
{
    public class FormController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

DoxaFinal/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DoxaMVC</title>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>
    <div class="d-flex flex-column min-vh-100">
    <header>
            <nav class="navbar navbar-light bg-white border-bottom box-shadow">
                <div class="container-fluid">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FinalMVC</a>
                </div>
            </nav>
    </header>
    <div class="container" style="flex:5;">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - DoxaMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    </div>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

DoxaFinal/Views/Shared/_LayoutSidebar.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DoxaMVC</title>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css"
          integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA=="
          crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body class="d-flex flex-column">
    <header>
        <nav class="navbar navbar-expand-sm navbar-light bg-white border-bottom box-shadow">
            <i class="fa-solid fa-bars ms-5"></i>
            <div class="container-fluid vw-100">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FinalMVC</a>
                <a class="nav-link nav-item" asp-action="Logout" asp-controller="Home">
                    <i class="fa-solid fa-right-from-bracket text-secondary"></i>
                </a>
            </div>
        </nav>
    </header>

    <div class="flex-grow-1 overflow-auto ">
        <div class="d-flex">
            <div class="pt-4 border-end  min-vh-100" style="flex: 1;">
                <a class="btn btn-outline-secondary w-100 border-0" asp-area="Login" asp-action="Index"
                   asp-controller="Form">Ürün girişi</a>
            </div>
            <div class="mb-3" style="flex: 7;">
                <main role="main">
                    @RenderBody()
                </main>
            </div>
        </div>

        <footer class="border-top footer text-muted">
            <div class="container">
                &copy; 2023 - DoxaMVC - <a asp-area="" asp-controller="Home"
                                           asp-action="Privacy">Privacy</a>
            </div>
        </footer>
    </div>

    <script src="/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html> 